model_dir: wmt_ende_transformer

data:
  train_features_file: data/train.en
  train_labels_file: data/train.de
  eval_features_file: data/valid.en
  eval_labels_file: data/valid.de
  source_vocabulary: data/wmtende.vocab
  target_vocabulary: data/wmtende.vocab

train:
  save_checkpoints_steps: 1000

eval:
  external_evaluators: BLEU

infer:
  batch_size: 32
